name: .NET Core

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: FranzDiebold/github-env-vars-action@v2

    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.100

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Testing CalculadoraTest
      uses: zyborg/dotnet-tests-report@v1
      with:
        project_path: CalculadoraTest1
        report_name: CalculadoraTest1
        report_title: Calculadora tests 1
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Testing CalculadoraTest2
      uses: zyborg/dotnet-tests-report@v1
      with:
        project_path: CalculadoraTest2
        report_name: CalculadoraTest2
        report_title: Calculadora tests 2
        github_token: ${{ secrets.GITHUB_TOKEN }}